# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Actionscan < Formula
  desc "Scan GitHub repos for vulnerable, malicious, and outdated GitHub Actions"
  homepage "https://github.com/krishnaduttPanchagnula/actionscan"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/krishnaduttPanchagnula/actionscan/releases/download/v0.1.5/actionscan_Darwin_x86_64.tar.gz"
      sha256 "17b3f2328f8959cc3e6f1e3eb2a05c3f389c99bee066e514cfba4791adc53b61"

      define_method(:install) do
        bin.install "actionscan"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/krishnaduttPanchagnula/actionscan/releases/download/v0.1.5/actionscan_Darwin_ARM64.tar.gz"
      sha256 "0619ab9a2ba93f163929e3cf1ec3a867e1f3bab8c1664be3e79cc7ff84b718c3"

      define_method(:install) do
        bin.install "actionscan"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/krishnaduttPanchagnula/actionscan/releases/download/v0.1.5/actionscan_Linux_x86_64.tar.gz"
      sha256 "cf50f21f785ffe6ba1b0f9a257c96e76329eb54eafeff12d1c69650ada105860"
      define_method(:install) do
        bin.install "actionscan"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/krishnaduttPanchagnula/actionscan/releases/download/v0.1.5/actionscan_Linux_ARM64.tar.gz"
      sha256 "7306fc95aa4146ded11460bb7d48674b4360a7f36f7be773d0dd72d310ecd510"
      define_method(:install) do
        bin.install "actionscan"
      end
    end
  end

  test do
    system "#{bin}/actionscan --help"
  end
end
